name: Bug report
description: Report a reproducible issue in hyper-evm-toolkit
title: "[Bug] "
labels:
  - type:fix
body:
  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight checklist
      options:
        - label: I searched existing issues and this is not a duplicate
          required: true
        - label: I can reproduce this on the latest main branch
          required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is broken?
      placeholder: A concise description of the bug
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run ...
        2. Call ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and traces
      description: Include forge/vitest output or stack traces
      render: shell

  - type: textarea
    id: environment
    attributes:
      label: Environment
      value: |
        - OS:
        - Foundry version (`forge --version`):
        - Node version (`node -v`):
        - npm version (`npm -v`):
    validations:
      required: true
